server:
  port: ${CONTAINER_PORT:8081}

spring:
  profiles:
    default: dev
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME}
    password: ${SPRING_RABBITMQ_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: com.condominiosaas.config.TablePreservingPhysicalNamingStrategy
    show-sql: false
    open-in-view: false

logging:
  level:
    root: ${LOGGING_LEVEL_ROOT:INFO}

management:
  endpoint:
    health:
      show-details: ${MANAGEMENT_ENDPOINT_HEALTH_SHOWDETAILS:never}

app:
  database:
    name: ${APP_DATABASE_NAME:Condominio_aspnet}
    create-if-missing: ${APP_DATABASE_CREATE_IF_MISSING:true}
  jwt:
    secret: ${APP_JWT_KEY}
    issuer: ${APP_JWT_ISSUER}
    audience: ${APP_JWT_AUDIENCE}
    expiration-minutes: ${APP_JWT_EXPIREMINUTES}